# Generated by Django 2.1 on 2018-09-12 09:09

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParseFieldsRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules', jsonfield.fields.JSONField()),
                ('model', models.CharField(max_length=32)),
                ('field', models.CharField(max_length=32)),
            ],
        ),
    ]
